### ISSUE TITLE
Test IDs that contain spaces are not fully parsed

### ISSUE THREAD

**Issue by SBoonstraABT** [ritchie46/pygef#63]
If a test ID contains spaces e.g. `#TESTID= CPT 01` then it is parsed as: `CPT`. This becomes problematic when a series of CPTs is enumerated in this way.

The desired solution for this would be to parse everything on the line behind `#TESTID= `, so in the example this would result in `CPT 01`.

**Comment by SBoonstraABT** [comment]
I have created a PR with a suggested solution: #64

**Comment by maarten-betman** [comment]
Experienced same issue. 
@martinapippi when do you plan to merge #64 and when fill you release a new version?

**Comment by martinapippi** [comment]
Hi guys, I merged it and made a tag, you can install it with `pip install git+https://github.com/ritchie46/pygef.git@0.4.1`.
@ritchie46 can you release it to pypi?
