### ISSUE TITLE
ValueError: Could not find been_jeffries. Check the spelling or classification not defined in the library

### ISSUE THREAD

**Issue by lmpjongen** [ritchie46/pygef#96]
This code gives an error. Can you fix this? Or am I doing something wrong? Thank you!
```
from pygef.gef import ParseGEF
File = ".GEF"
gef = ParseGEF(File)
gef.plot(classification='been_jeffries',water_level_NAP= -1,min_thickness= 0.2,show=True)
```

**Comment by tversteeg** [comment]
What is the pygef version you are using? Can you also post the error?

**Comment by lmpjongen** [comment]
Version: '0.4'
The above script returns this error for me:
"ValueError: Could not find been_jeffries. Check the spelling or classification not defined in the library"

**Comment by tversteeg** [comment]
Did you install it with `pip install pygef` or `pip install git+https://github.com/ritchie46/pygef.git`? If it's the latter that might be the case why it's not working, you should install it with the former.

**Comment by martinapippi** [comment]
> This code gives an error. Can you fix this? Or am I doing something wrong? Thank you!
> 
> ```
> from pygef.gef import ParseGEF
> File = ".GEF"
> gef = ParseGEF(File)
> gef.plot(classification='been_jeffries',water_level_NAP= -1,min_thickness= 0.2,show=True)
> ```

You have a spelling error, you should use "been_jefferies" not "been_jeffries"
